[http]
host = "0.0.0.0"  # Позволяет принимать подключения извне (важно для Docker)
port = 8080
cache_ttl = "10m"

[db]
host = "db"
port = 5432
user = "demoservice"
password = "demoservice_pass"
database = "demoservice_db"
sslmode = "disable"
max_conns = 10
min_conns = 2
health_check_period = "1m"

[kafka]
# Внутри Docker-сети используем адрес 'redpanda:9092'
brokers = ["redpanda:9092"]
topic = "orders"
group_id = "order-processor"
dlq_topic = "orders_dlq"

[telemetry]
enabled = false
service_name = "web_demoservice"
otlp_endpoint = "localhost:4317"
otlp_insecure = true
sample_ratio = 1.0

[metrics]
enabled = true
path = "/metrics"
